from typing import overload, Sequence
from . import ir

class AffineForOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @property
    def body(self) -> ir.Block: ...
    @overload
    @staticmethod
    def create(
        arg0: ir.AlloOpBuilder, arg1: int, arg2: int, arg3: int = 1, /
    ) -> AffineForOp: ...
    @overload
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder,
        lb_operands: Sequence[ir.Value],
        lb_map: ir.AffineMap,
        ub_operands: Sequence[ir.Value],
        ub_map: ir.AffineMap,
        step: int = 1,
    ) -> AffineForOp: ...
    @property
    def constant_lower_bound(self) -> int: ...
    @property
    def constant_upper_bound(self) -> int: ...
    @property
    def induction_var(self) -> ir.BlockArgument: ...
    @property
    def lower_bound(self) -> ir.AffineBound: ...
    @property
    def step(self) -> int: ...
    @property
    def upper_bound(self) -> ir.AffineBound: ...
    def has_constant_bounds(self) -> bool: ...
    @property
    def has_constant_lower_bound(self) -> bool: ...
    @property
    def has_constant_upper_bound(self) -> bool: ...

class AffineIfOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder,
        set: ir.IntegerSet,
        operands: Sequence[ir.Value],
        with_else: bool = False,
    ) -> AffineIfOp: ...
    @property
    def else_block(self) -> ir.Block: ...
    @property
    def integer_set(self) -> ir.IntegerSet: ...
    @property
    def then_block(self) -> ir.Block: ...
