from typing import overload, Sequence
from . import ir

class AffineForOp(ir.OpState):
    def get_body(self) -> ir.Block: ...
    @overload
    def __init__(
        self, arg0: ir.AlloOpBuilder, arg1: int, arg2: int, arg3: int = 1, /
    ) -> None: ...
    @overload
    def __init__(
        self,
        builder: ir.AlloOpBuilder,
        lb_operands: Sequence[ir.Value],
        lb_map: ir.AffineMap,
        ub_operands: Sequence[ir.Value],
        ub_map: ir.AffineMap,
        step: int = 1,
    ) -> None: ...
    def get_constant_lower_bound(self) -> int: ...
    def get_constant_upper_bound(self) -> int: ...
    def get_induction_var(self) -> ir.BlockArgument: ...
    def get_lower_bound(self) -> ir.AffineBound: ...
    def get_step(self) -> int: ...
    def get_upper_bound(self) -> ir.AffineBound: ...
    def has_constant_bounds(self) -> bool: ...
    def get_has_constant_lower_bound(self) -> bool: ...
    def get_has_constant_upper_bound(self) -> bool: ...

class AffineIfOp(ir.OpState):
    def __init__(
        self,
        builder: ir.AlloOpBuilder,
        set: ir.IntegerSet,
        operands: Sequence[ir.Value],
        with_else: bool = False,
    ) -> None: ...
    def get_else_block(self) -> ir.Block: ...
    def get_integer_set(self) -> ir.IntegerSet: ...
    def get_then_block(self) -> ir.Block: ...

class AffineLoadOp(ir.OpState):
    def __init__(
        self,
        builder: ir.AlloOpBuilder,
        memref: ir.Value,
        map: ir.AffineMap,
        operands: Sequence[ir.Value],
    ) -> None: ...
    def get_value(self) -> ir.Value: ...
    def get_memref(self) -> ir.Value: ...
    def get_map(self) -> ir.AffineMap: ...
    def get_operands(self) -> list[ir.Value]: ...

class AffineStoreOp(ir.OpState):
    def __init__(
        self,
        builder: ir.AlloOpBuilder,
        value: ir.Value,
        memref: ir.Value,
        map: ir.AffineMap,
        operands: Sequence[ir.Value],
    ) -> None: ...
    def get_value(self) -> ir.Value: ...
    def get_memref(self) -> ir.Value: ...
    def get_map(self) -> ir.AffineMap: ...
    def get_operands(self) -> list[ir.Value]: ...

class AffineApplyOp(ir.OpState):
    def __init__(
        self,
        builder: ir.AlloOpBuilder,
        map: ir.AffineMap,
        operands: Sequence[ir.Value],
    ) -> None: ...
    def get_map(self) -> ir.AffineMap: ...
    def get_operands(self) -> list[ir.Value]: ...
