from typing import overload
from . import ir

class AddFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class AddIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class AndIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class BitcastOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class CmpFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, pred: int, lhs: ir.Value, rhs: ir.Value
    ) -> ir.Value: ...

class CmpIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, pred: int, lhs: ir.Value, rhs: ir.Value
    ) -> ir.Value: ...

class ConstantFloatOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @overload
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, type: ir.F16Type, value: float
    ) -> ir.Value: ...
    @overload
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, type: ir.F32Type, value: float
    ) -> ir.Value: ...
    @overload
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, type: ir.F64Type, value: float
    ) -> ir.Value: ...
    @overload
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, type: ir.BF16Type, value: float
    ) -> ir.Value: ...

class ConstantIndexOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, value: int) -> ir.Value: ...

class ConstantIntOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, type: ir.IntegerType, value: int
    ) -> ir.Value: ...

class ConstantOp(ir.OpState):
    def __init__(*args, **kwargs): ...

class DivFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class DivSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class DivUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class ExtFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class ExtSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class ExtUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class FPToSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class FPToUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class FmaOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, a: ir.Value, b: ir.Value, c: ir.Value
    ) -> ir.Value: ...

class IndexCastOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder,
        dst_type: ir.Type,
        src: ir.Value,
    ) -> ir.Value: ...

class MaxNumFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MaxSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MaxUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MaximumFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MinNumFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MinSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MinUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MinimumFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MulFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class MulIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class NegFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class OrIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class RemFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class RemSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class RemUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class SIToFPOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class SelectOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder,
        condition: ir.Value,
        true_value: ir.Value,
        false_value: ir.Value,
    ) -> ir.Value: ...

class ShLIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class ShRSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class ShRUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class SubFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class SubIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class TruncFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class TruncIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class UIToFPOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, src: ir.Value, dst_type: ir.Type
    ) -> ir.Value: ...

class XOrIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class CeilDivSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class CeilDivUIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...

class FloorDivSIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, lhs: ir.Value, rhs: ir.Value) -> ir.Value: ...
