from typing import Sequence
from enum import Enum
from . import ir

class FuncOp(ir.OpState):
    def add_entry_block(self) -> ir.Block: ...
    def __init__(
        self, builder: ir.AlloOpBuilder, name: str, type: ir.FunctionType
    ) -> None: ...
    def get_arg_at(self, idx: int) -> ir.BlockArgument: ...
    def get_func_type(self) -> ir.FunctionType: ...
    def get_num_args(self) -> int: ...
    def set_arg_attr(self, arg_no: int, name: str, attr: ir.Attribute) -> None: ...
    def set_type(self, type: ir.Type) -> None: ...
    def get_func_name(self) -> str: ...

class CallOp(ir.OpState):
    def __init__(
        self, builder: ir.AlloOpBuilder, func: FuncOp, args: Sequence[ir.Value]
    ) -> None: ...

class ReturnOp(ir.OpState):
    def __init__(
        self, builder: ir.AlloOpBuilder, operands: Sequence[ir.Value]
    ) -> None: ...
