from typing import Sequence
from enum import Enum
from . import ir

class FuncOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    def add_entry_block(self) -> ir.Block: ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, fn_name: str, fn_ty: ir.FunctionType, /
    ) -> FuncOp: ...
    def get_arg_at(self, idx: int) -> ir.BlockArgument: ...
    @property
    def func_type(self) -> ir.FunctionType: ...
    @property
    def num_args(self) -> int: ...
    def set_arg_attr(self, arg_no: int, name: str, attr: ir.Attribute) -> None: ...
    def set_type(self, type: ir.Type) -> None: ...
    @property
    def func_name(self) -> str: ...

class CallOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, func: FuncOp, args: Sequence[ir.Value]
    ) -> CallOp: ...

class ReturnOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, operands: Sequence[ir.Value]) -> ReturnOp: ...
