from typing import Any, Dict, Sequence, Union, overload, TypeVar

T = TypeVar("T")

class Context:
    def __init__(self) -> None: ...
    def get_loaded_dialects(self) -> list[str]: ...
    def load_dialects(self) -> None: ...
    def load_transform_dialects(self) -> None: ...
    def printOpOnDiagnostic(self, enable: bool) -> None: ...
    def printStackTraceOnDiagnostic(self, enable: bool) -> None: ...

class InsertPoint:
    def __init__(self) -> None: ...
    def get_block(self) -> Block: ...

class OpBuilder:
    @overload
    def __init__(self, context: Context) -> None: ...
    @overload
    def __init__(self, operation: Operation) -> None: ...
    @overload
    def __init__(self, region: Region) -> None: ...
    def get_context(self) -> Context: ...
    def set_insertion_point(self, op: Operation) -> None: ...
    def set_insertion_point_after(self, op: Operation) -> None: ...
    def set_insertion_point_to_start(self, block: Block) -> None: ...
    def set_insertion_point_to_end(self, block: Block) -> None: ...
    def save_insertion_point(self) -> InsertPoint: ...
    def restore_insertion_point(self, ip: InsertPoint) -> None: ...
    def get_affine_dim(self, dim: int) -> AffineExpr: ...
    def get_affine_symbol(self, sym: int) -> AffineExpr: ...
    def get_affine_constant(self, value: int) -> AffineExpr: ...
    def get_unknown_loc(self) -> Location: ...
    def create_free_block(
        self,
        region: Region,
        arg_types: Sequence[Type] = [],
    ) -> Block: ...
    def create_block_in_region(
        self,
        loc: Location,
        region: Region,
        arg_types: Sequence[Type],
    ) -> Block: ...
    def get_dict_attr(self, dict: Dict[str, Attribute]) -> DictionaryAttr: ...
    def get_string_attr(self, value: str) -> StringAttr: ...

class AlloOpBuilder(OpBuilder):
    @overload
    def __init__(self, context: Context) -> None: ...
    @overload
    def __init__(self, operation: Operation) -> None: ...
    def get_loc(self) -> Location: ...
    def set_loc(self, new_loc: Location) -> None: ...
    def set_unknown_loc(self) -> None: ...
    def get_insertion_point_and_loc(self) -> tuple[InsertPoint, Location]: ...
    def set_insertion_point_and_loc(
        self, ip: InsertPoint, new_loc: Location
    ) -> None: ...

class Location:
    @overload
    def __init__(self, context: Context) -> None: ...
    @overload
    def __init__(
        self, filename: str, line: int, col: int, context: Context
    ) -> None: ...
    @overload
    def __init__(self, child_loc: Location, name: str, context: Context) -> None: ...
    def __str__(self) -> str: ...
    def get_context(self) -> Context: ...
    def set_name(self, name: str) -> None: ...
    def get_col(self) -> int: ...
    def get_line(self) -> int: ...
    def get_filename(self) -> str: ...
    def get_name(self) -> str: ...

class Type:
    @staticmethod
    def cast(other: T) -> T: ...
    def __init__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...

class Value:
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def set_attr(self, name: str, attr: Attribute) -> None: ...
    def get_context(self) -> Context: ...
    def get_loc(self) -> Location: ...
    def set_loc(self, loc: Location) -> None: ...
    def get_type(self) -> Type: ...
    def set_type(self, type: Type) -> None: ...
    def replace_all_uses_with(self, val: Value) -> None: ...

class Attribute:
    @staticmethod
    def cast(other: T) -> T: ...
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def get_context(self) -> Context: ...

class Region:
    def get_context(self) -> Context: ...
    def get_parent_region(self) -> Region: ...
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def front(self) -> Block: ...
    def back(self) -> Block: ...
    def push_back(self, block: Block) -> None: ...
    def push_front(self, block: Block) -> None: ...
    def emplace_block(self) -> Block: ...

class Block:
    def get_arg_at(self, idx: int) -> BlockArgument: ...
    def get_args(self) -> list[Value]: ...
    def get_arg_types(self) -> list[Type]: ...
    def add_arg(self, type: Type) -> BlockArgument: ...
    def add_arg_at_loc(self, type: Type, loc: Location) -> BlockArgument: ...
    def get_num_args(self) -> int: ...
    def move_before(self, dst: Block) -> None: ...
    def insert_before(self, block: Block) -> None: ...
    def get_parent_region(self) -> Region: ...
    def get_parent_op(self) -> Operation: ...
    def __str__(self) -> str: ...
    def get_terminator(self) -> Operation: ...
    def erase(self) -> None: ...

class Operation:
    def get_context(self) -> Context: ...
    def get_loc(self) -> Location: ...
    def get_name(self) -> str: ...

class OpState:
    def get_context(self) -> Context: ...
    def get_loc(self) -> Location: ...
    def set_attr(self, name: str, attr: Attribute) -> None: ...
    def get_attribute(self, attr_name: str) -> Attribute | None: ...
    def get_num_operands(self) -> int: ...
    def get_operand_at(self, idx: int) -> Value: ...
    def get_num_results(self) -> int: ...
    def get_result_at(self, idx: int) -> OpResult: ...
    def get_num_regions(self) -> int: ...
    def get_region_at(self, idx: int) -> Region: ...
    def get_block(self) -> Block: ...
    def get_operation(self) -> Operation: ...
    def __str__(self) -> str: ...
    def dump_with_loc(self) -> str: ...
    def verify(self) -> bool: ...

class ModuleOp(OpState):
    def __init__(self, builder: AlloOpBuilder) -> None: ...
    def get_body(self) -> Block: ...
    def push_back(self, op: Operation) -> None: ...

class FunctionType(Type):
    @staticmethod
    def get(
        arg_types: Sequence[Type],
        ret_types: Sequence[Type],
        context: Context,
    ) -> FunctionType: ...
    def get_arg_types(self) -> list[Type]: ...
    def get_res_types(self) -> list[Type]: ...
    def get_num_args(self) -> int: ...
    def get_num_results(self) -> int: ...

class NoneType(Type):
    @staticmethod
    def get(context: Context) -> NoneType: ...

class IntegerType(Type):
    @staticmethod
    def get(width: int, context: Context) -> IntegerType: ...
    @staticmethod
    def get_width(ty: Type) -> int: ...

class IndexType(Type):
    @staticmethod
    def get(context: Context) -> IndexType: ...

class FloatType(Type): ...

class F16Type(Type):
    @staticmethod
    def get(context: Context) -> F16Type: ...

class F32Type(Type):
    @staticmethod
    def get(context: Context) -> F32Type: ...

class F64Type(Type):
    @staticmethod
    def get(context: Context) -> F64Type: ...

class BF16Type(Type):
    @staticmethod
    def get(context: Context) -> BF16Type: ...

class UnrankedTensorType(Type):
    @staticmethod
    def get(element_type: Type) -> UnrankedTensorType: ...
    def get_element_type(self) -> Type: ...

class RankedTensorType(Type):
    @staticmethod
    def get(
        shape: Sequence[int],
        element_type: Type,
        encoding: Attribute | None = None,
    ) -> RankedTensorType: ...
    def get_encoding(self) -> Attribute: ...
    def get_element_type(self) -> Type: ...
    def get_shape(self) -> list[int]: ...
    def get_rank(self) -> int: ...
    def get_dim_size_at(self, index: int) -> int: ...
    def set_element_type(self, type: Type) -> RankedTensorType: ...

class UnrankedMemRefType(Type):
    @staticmethod
    def get(
        element_type: Type,
        memory_space: Attribute | None = None,
    ) -> UnrankedMemRefType: ...
    def get_element_type(self) -> Type: ...

class MemRefType(Type):
    @staticmethod
    def get(
        shape: Sequence[int],
        element_type: Type,
        affine_maps: AffineMap,
        memory_space: Attribute | None = None,
    ) -> MemRefType: ...
    def get_element_type(self) -> Type: ...
    def get_shape(self) -> list[int]: ...
    def get_rank(self) -> int: ...

class BlockArgument(Value):
    def get_arg_number(self) -> int: ...
    def get_owner(self) -> Block: ...

class OpResult(Value):
    def get_owner(self) -> Operation: ...
    def get_res_no(self) -> int: ...

class IntegerAttr(Attribute):
    @staticmethod
    def get(ty: Type, value: int) -> IntegerAttr: ...
    def get_signless(self) -> int: ...
    def get_signed(self) -> int: ...
    def get_unsigned(self) -> int: ...

class FloatAttr(Attribute):
    @staticmethod
    def get(ty: Type, value: float) -> FloatAttr: ...

class UnitAttr(Attribute):
    @staticmethod
    def get(context: Context) -> UnitAttr: ...

class StringAttr(Attribute):
    @staticmethod
    def get(value: str, context: Context) -> StringAttr: ...
    def get_value(self) -> str: ...

class BoolAttr(Attribute):
    @staticmethod
    def get(value: bool, context: Context) -> BoolAttr: ...

class DenseI32ArrayAttr(Attribute):
    @staticmethod
    def get(context: Context, values: Sequence[int]) -> DenseI32ArrayAttr: ...
    def size(self) -> int: ...

class DenseI64ArrayAttr(Attribute):
    @staticmethod
    def get(context: Context, values: Sequence[int]) -> DenseI64ArrayAttr: ...
    def size(self) -> int: ...

class FlatSymbolRefAttr(Attribute):
    @staticmethod
    def get(value: str, context: Context) -> FlatSymbolRefAttr: ...
    def get_value(self) -> str: ...

class StridedLayoutAttr(Attribute):
    @staticmethod
    def get(
        context: Context,
        offset: int,
        strides: Sequence[int],
    ) -> StridedLayoutAttr: ...
    def get_strides(self) -> list[int]: ...
    def get_offset(self) -> int: ...

class DictionaryAttr(Attribute):
    @staticmethod
    def get(context: Context, d: Dict[str, Attribute]) -> DictionaryAttr: ...

class TypeAttr(Attribute):
    @staticmethod
    def get(type: Type) -> TypeAttr: ...
    def get_type(self) -> Type: ...

class IntegerSet:
    @staticmethod
    def get(
        num_dims: int,
        num_symbols: int,
        constraints: Sequence[AffineExpr],
        context: Sequence[int],
    ) -> IntegerSet: ...
    def get_num_dims(self) -> int: ...
    def get_num_symbols(self) -> int: ...
    def get_num_constraints(self) -> int: ...
    def __str__(self) -> str: ...

class AffineExpr:
    def __str__(self) -> str: ...
    def __add__(self, other: AffineExpr) -> AffineExpr: ...
    def __sub__(self, other: AffineExpr) -> AffineExpr: ...
    def __mul__(self, other: AffineExpr) -> AffineExpr: ...
    def __floordiv__(self, other: AffineExpr) -> AffineExpr: ...
    def __truediv__(self, other: AffineExpr) -> AffineExpr: ...
    def __mod__(self, other: AffineExpr) -> AffineExpr: ...

class AffineMap:
    @staticmethod
    def get(
        dim_sizes: Sequence[int],
        symbol_sizes: Sequence[int],
        results: Sequence[AffineExpr],
        context: Context,
    ) -> AffineMap: ...
    @staticmethod
    def get_identity(dim_count: int, context: Context) -> AffineMap: ...
    def get_num_dims(self) -> int: ...
    def get_num_symbols(self) -> int: ...
    def get_num_results(self) -> int: ...
    def get_sub_map(self, *args, **kwargs) -> AffineMap: ...
    def __str__(self) -> str: ...
    def simplify(self) -> None: ...

class AffineBound:
    def get_map(self) -> AffineMap: ...
    def get_operands(self) -> list[Value]: ...

def fully_compose_affine_map(
    map: AffineMap, operands: Sequence[Value]
) -> tuple[AffineMap, list[Value]]: ...
def isa(op: Operation | OpState, cls: type[Any]) -> bool: ...
def cast(op: Operation | OpState, cls: type[T]) -> T: ...
def dyn_cast(op: Operation | OpState, cls: type[T]) -> T | None: ...
