from typing import overload, Sequence, Union, Dict, Any

from dataclasses import dataclass

class Context:
    def __init__(self) -> None: ...
    @property
    def loaded_dialects(self) -> list[str]: ...
    def load_dialects(self) -> None: ...
    def load_transform_dialects(self) -> None: ...
    def printOpOnDiagnostic(self, enable: bool) -> None: ...
    def printStackTraceOnDiagnostic(self, enable: bool) -> None: ...

class Location:
    @overload
    def __init__(self, child_loc: Location, name: str, context: Context) -> None: ...
    @overload
    def __init__(self, context: Context) -> None: ...
    @overload
    def __init__(
        self, filename: str, line: int, col: int, context: Context
    ) -> None: ...
    @property
    def col(self) -> int: ...
    @property
    def context(self) -> Context: ...
    @property
    def filename(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...

class Type:
    def __init__(self) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __str__(self) -> str: ...

class FloatType(Type):
    def __init__(*args, **kwargs): ...

class BF16Type(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> BF16Type: ...

class F16Type(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> F16Type: ...

class F32Type(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> F32Type: ...

class F64Type(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> F64Type: ...

class FunctionType(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(
        arg_types: Sequence[Type],
        ret_types: Sequence[Type],
        context: Context,
    ) -> FunctionType: ...
    @property
    def arg_types(self) -> list[Type]: ...
    @property
    def num_args(self) -> int: ...
    @property
    def num_results(self) -> int: ...
    @property
    def res_types(self) -> list[Type]: ...

class IndexType(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> IndexType: ...
    @staticmethod
    def isa(ty: Type) -> bool: ...

class IntegerType(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(width: int, context: Context) -> IntegerType: ...
    @staticmethod
    def get_width(ty: Type) -> int: ...

class ModuleOp(OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: AlloOpBuilder) -> ModuleOp: ...
    def push_back(self, arg: Operation, /) -> None: ...
    @property
    def body(self) -> Block: ...
    from .func import FuncOp
    def lookup_function(self, name: str) -> FuncOp: ...

class NoneType(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> NoneType: ...

class RankedTensorType(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(
        shape: Sequence[int],
        element_type: Type,
        encoding: Union[Attribute, None] = None,
    ) -> RankedTensorType: ...
    def get_dim_size_at(self, index: int) -> int: ...
    @property
    def element_type(self) -> Type: ...
    @property
    def encoding(self) -> Attribute: ...
    @property
    def rank(self) -> int: ...
    @property
    def shape(self) -> list[int]: ...
    def set_element_type(self, type: Type) -> RankedTensorType: ...

class MemRefType(Type):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(
        shape: Sequence[int],
        element_type: Type,
        affine_map: AffineMap,
        memory_space: Attribute | None = None,
    ) -> MemRefType: ...
    @property
    def element_type(self) -> Type: ...
    @property
    def rank(self) -> int: ...
    @property
    def shape(self) -> list[int]: ...

class Attribute:
    def __init__(self) -> None: ...
    @property
    def context(self) -> Context: ...

class AffineExpr:
    def __init__(self) -> None: ...

class AffineMap:
    def __init__(self) -> None: ...
    @staticmethod
    def get(
        dim_sizes: Sequence[int],
        symbol_sizes: Sequence[int],
        results: Sequence[AffineExpr],
        context: Context,
    ) -> AffineMap: ...
    @staticmethod
    def get_identity(dim_count: int, context: Context) -> AffineMap: ...
    @property
    def num_dims(self) -> int: ...
    @property
    def num_results(self) -> int: ...
    @property
    def num_symbols(self) -> int: ...

class AffineMapAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(map: AffineMap, context: Context) -> AffineMapAttr: ...
    @property
    def map(self) -> AffineMap: ...

class BoolAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(value: bool, context: Context) -> BoolAttr: ...

class DenseI32ArrayAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context, values: Sequence[int]) -> DenseI32ArrayAttr: ...
    def size(self) -> int: ...

class DenseI64ArrayAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context, values: Sequence[int]) -> DenseI64ArrayAttr: ...
    def size(self) -> int: ...

class IntegerAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(ty: Type, value: int) -> IntegerAttr: ...
    def get_signed(self) -> int: ...
    def get_signless(self) -> int: ...
    def get_unsigned(self) -> int: ...

class StringAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(value: str, context: Context) -> StringAttr: ...
    @property
    def value(self) -> str: ...

class UnitAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context) -> UnitAttr: ...

class IntegerSet:
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(
        num_dims: int,
        num_symbols: int,
        constraints: Sequence[AffineExpr],
        context: Sequence[int],
    ) -> IntegerSet: ...
    @property
    def num_constraints(self) -> int: ...
    @property
    def num_dims(self) -> int: ...
    @property
    def num_symbols(self) -> int: ...

class Value:
    def __init__(self) -> None: ...
    @property
    def context(self) -> Context: ...
    @property
    def loc(self) -> Location: ...
    @loc.setter
    def loc(self, loc: Location) -> None: ...
    @property
    def type(self) -> Type: ...
    @type.setter
    def type(self, type: Type) -> None: ...
    def replace_all_uses_with(self, val: Value) -> None: ...
    def set_attr(self, name: str, attr: Attribute) -> None: ...
    def erase(self) -> None: ...

class BlockArgument(Value):
    def __init__(*args, **kwargs): ...
    @property
    def arg_number(self) -> int: ...
    @property
    def owner(self) -> Block: ...

class OpResult(Value):
    def __init__(*args, **kwargs): ...
    @property
    def owner(self) -> Operation: ...
    @property
    def res_no(self) -> int: ...

class Operation:
    def __init__(self) -> None: ...
    @property
    def context(self) -> Context: ...
    @property
    def loc(self) -> Location: ...
    @property
    def name(self) -> str: ...

class Block:
    def __init__(self) -> None: ...
    def add_arg(self, type: Type) -> BlockArgument: ...
    def add_arg_at_loc(self, type: Type, loc: Location) -> BlockArgument: ...
    def erase(self) -> None: ...
    def get_arg_at(self, arg: int, /) -> BlockArgument: ...
    @property
    def parent_region(self) -> Region: ...
    def has_return(self) -> bool: ...
    def has_terminator(self) -> bool: ...
    def remove_terminator(self) -> None: ...
    def insert_before(self, block: Block) -> None: ...
    def merge_before(self, dst: Block) -> None: ...
    def move_before(self, arg: Block, /) -> None: ...
    @property
    def num_args(self) -> int: ...
    def replace_use_in_block_with(self, old_val: Value, new_val: Value) -> None: ...

class Region:
    def __init__(*args, **kwargs): ...
    def back(self) -> Block: ...
    def emplace_block(self) -> Block: ...
    def empty(self) -> bool: ...
    def front(self) -> Block: ...
    @property
    def context(self) -> Context: ...
    @property
    def parent_region(self) -> Region: ...
    def push_back(self, block: Block) -> None: ...
    def push_front(self, block: Block) -> None: ...
    def size(self) -> int: ...

class OpState:
    def __init__(self) -> None: ...
    def append_operand(self, arg: Value, /) -> None: ...
    @property
    def block(self) -> Block: ...
    @property
    def context(self) -> Context: ...
    @property
    def loc(self) -> Location: ...
    @property
    def num_operands(self) -> int: ...
    @property
    def num_regions(self) -> int: ...
    @property
    def num_results(self) -> int: ...
    def get_operand_at(self, idx: int) -> Value: ...
    @property
    def operation(self) -> Operation: ...
    def get_region_at(self, arg: int, /) -> Region: ...
    def get_result_at(self, arg: int, /) -> OpResult: ...
    def set_attr(self, arg0: str, arg1: Attribute, /) -> None: ...
    def verify(self) -> bool: ...

class InsertPoint:
    def __init__(self) -> None: ...
    @property
    def block(self) -> Block: ...

class OpBuilder:
    @overload
    def __init__(self, arg: Region, /) -> None: ...
    @overload
    def __init__(self, arg: Context, /) -> None: ...
    @overload
    def __init__(self, arg: Operation, /) -> None: ...
    def create_block(self) -> Block: ...
    def create_block_in_region(
        self, arg0: Region, arg1: Sequence[Type], /
    ) -> Block: ...
    def get_affine_constant(self, value: int) -> AffineExpr: ...
    def get_affine_dim(self, dim: int) -> AffineExpr: ...
    def get_affine_symbol(self, sym: int) -> AffineExpr: ...
    @property
    def context(self) -> Context: ...
    def get_unknown_loc(self) -> Location: ...
    def restore_insertion_point(self, ip: InsertPoint) -> None: ...
    def save_insertion_point(self) -> InsertPoint: ...
    def set_insertion_point(self, op: Operation) -> None: ...
    def set_insertion_point_after(self, op: Operation) -> None: ...
    def set_insertion_point_to_end(self, block: Block) -> None: ...
    def set_insertion_point_to_start(self, block: Block) -> None: ...
    def get_dict_attr(self, d: Dict[str, Attribute]) -> DictionaryAttr: ...
    def get_str_attr(self, attr: str) -> StringAttr: ...

class AlloOpBuilder(OpBuilder):
    @overload
    def __init__(self, arg: Operation, /) -> None: ...
    @overload
    def __init__(self, arg: Context, /) -> None: ...
    def get_insertion_point_and_loc(
        self,
    ) -> tuple[InsertPoint, Location]: ...
    @property
    def loc(self) -> Location: ...
    @loc.setter
    def loc(self, new_loc: Location) -> None: ...
    def set_insertion_point_and_loc(
        self, ip: InsertPoint, new_loc: Location
    ) -> None: ...
    def set_unknown_loc(self) -> None: ...

class AffineBound:
    def __init__(self) -> None: ...
    @property
    def map(self) -> AffineMap: ...
    @property
    def operands(self) -> list[Value]: ...

class FloatAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(type: Type, value: float) -> FloatAttr: ...

class DictionaryAttr(Attribute):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def get(context: Context, d: Dict[str, Attribute]) -> DictionaryAttr: ...

def verify(arg: Operation, /) -> bool: ...

OP_IDENTIFIER_ATTR_NAME: str

def parse_proxy_tree(module: ModuleOp) -> ProxyNode: ...
def complete_op_identifiers(
    module: ModuleOp, overwrite: bool = False
) -> Dict[str, int]: ...
def finalize_transform(module: ModuleOp) -> Dict[str, int]: ...
def parse_from_string(context: Context, s: str) -> ModuleOp: ...
def parse_from_file(context: Context, filename: str) -> ModuleOp: ...
@dataclass
class ProxyNode:
    parent: ProxyNode | None
    children: list[ProxyNode]
    values: list[ProxyValueInfo]
    op: Operation
    op_kind: str
    hierarchy_name: str
    op_identifier: str
    def __str__(self): ...

@dataclass
class ProxyValueInfo:
    value: Value
    value_identifier: str
    owner_op_identifier: str
    owner_op_kind: str
    source_kind: str
    source_index: int
    type_str: str
    is_memref: bool
    root_kind: str
    root_owner_identifier: str
    root_arg_number: int
