from . import ir

class AbsFOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class AbsIOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class CeilOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class CosOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class ErfOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class Exp2Op(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class ExpOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class FloorOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class Log2Op(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class LogOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class RsqrtOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class SinOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class SqrtOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...

class PowFOp(ir.OpState):
    def __init__(
        self, builder: ir.AlloOpBuilder, base: ir.Value, exp: ir.Value
    ) -> None: ...

class TanOp(ir.OpState):
    def __init__(self, builder: ir.AlloOpBuilder, val: ir.Value) -> None: ...
