from . import ir

class AbsFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class AbsIOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class CeilOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class CosOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class ErfOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class Exp2Op(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class ExpOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class FloorOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class Log2Op(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class LogOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class RsqrtOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class SinOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class SqrtOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...

class PowFOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(
        builder: ir.AlloOpBuilder, base: ir.Value, exp: ir.Value
    ) -> ir.Value: ...

class TanOp(ir.OpState):
    def __init__(*args, **kwargs): ...
    @staticmethod
    def create(builder: ir.AlloOpBuilder, val: ir.Value) -> ir.Value: ...
