
//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
#include <cstdint>
#include "/xls_builtin.h"
#include "xls_int.h"

template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

/// This is top function.

// ---- TestBlock with embedded function (register mode) ----
class TestBlock {
public:
  __xls_channel<int, __xls_channel_dir_In> v0_in;
  __xls_channel<int, __xls_channel_dir_In> v1_in;
  __xls_channel<int, __xls_channel_dir_Out> out;

  #pragma hls_top
  void gemm() {
    // L2
     int v0[4][4];
     int v1[4][4];
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       v0[_idx / 4][_idx % 4] = v0_in.read();
     }
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       v1[_idx / 4][_idx % 4] = v1_in.read();
     }
     int C[4][4] /* int C[4][4] */;	// L4
     #pragma hls_unroll yes
     for (int v3 = 0; v3 < 4; v3++) {	// L5
       #pragma hls_unroll yes
       for (int v4 = 0; v4 < 4; v4++) {	// L5
         C[v3][v4] = 0;	// L5
       }
     }
     #pragma hls_pipeline_init_interval 1
     for (int i = 0; i < 4; i++) {	// L6
       #pragma hls_unroll yes
       for (int j = 0; j < 4; j++) {	// L7
         #pragma hls_unroll yes
         for (int k = 0; k < 4; k++) {	// L8
           int v8 = v0[i][k];	// L9
           int v9 = v1[k][j];	// L10
           long long v10 = v8;	// L11
           long long v11 = v9;	// L12
           long long v12 = v10 * v11;	// L13
           int v13 = C[i][j];	// L14
           int v14 = v12;	// L15
           int v15 = v13 + v14;	// L16
           C[i][j] = v15;	// L17
         }
       }
     }
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       out.write(C[_idx / 4][_idx % 4]);
     }

  }
};
