
//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
#include <cstdint>
#include "/xls_builtin.h"
#include "xls_int.h"

template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

/// This is top function.
#pragma hls_top
int expr(
  int v0,
  int v1
) {	// L2
  ac_int<33, true> v2 = v0;	// L3
  ac_int<33, true> v3 = v1;	// L4
  ac_int<33, true> v4 = v2 + v3;	// L5
  ac_int<65, true> v5 = v4;	// L6
  ac_int<65, true> v6 = v5 * 2;	// L12
  ac_int<66, true> v7 = v6;	// L13
  ac_int<66, true> v8 = v0;	// L14
  ac_int<66, true> v9 = v7 - v8;	// L15
  int v10 = v9;	// L16
  return v10;
}

