# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import numpy as np
from .utils import format_str
from ..ir.transform import find_func_in_module
from ..utils import get_func_inputs_outputs

header = """
//=============================================================================
// Auto generated by Allo
//=============================================================================

#include <iostream>
#include <fstream>
#include <vector>
#include <iomanip>
#include <cstring>
#include <cstdlib>

// Catapult HLS headers
#include <ac_int.h>
#include <ac_fixed.h>
#include <ac_channel.h>

#include "kernel.h"

using namespace std;
"""

main_header = """
int main(int argc, char** argv) {
"""

dtype_size_map = {
    "int8": 1,
    "int16": 2,
    "int32": 4,
    "int64": 8,
    "uint8": 1,
    "uint16": 2,
    "uint32": 4,
    "uint64": 8,
    "float16": 2,
    "float32": 4,
    "float64": 8,
}

ctype_map = {
    "bf16": "std::bfloat16_t",
    "f32": "float",
    "f64": "double",
    "i8": "int8_t",
    "i16": "int16_t",
    "i32": "int32_t",
    "i64": "int64_t",
    "ui1": "bool",
    "ui8": "uint8_t",
    "ui16": "uint16_t",
    "ui32": "uint32_t",
    "ui64": "uint64_t",
}


def codegen_host(top, module):
    """Generate C++ host code for Catapult HLS functional simulation.

    Parameters
    ----------
    top : str
        Top-level function name
    module : Module
        MLIR module containing the function
    """
    func = find_func_in_module(module, top)
    inputs, outputs = get_func_inputs_outputs(func)

    out_str = format_str(header, indent=0, strip=False)
    out_str += format_str(main_header, indent=0, strip=False)

    # Process inputs
    for i, (in_dtype, in_shape) in enumerate(inputs):
        # Read from file (text mode)
        out_str += format_str(f'ifstream ifile{i}("input{i}.data");', 4)
        out_str += format_str(f"if (!ifile{i}.is_open()) {{", 4)
        out_str += format_str('cerr << "Error: Could not open input file.\\n";', 8)
        out_str += format_str("return 1;", 8)
        out_str += format_str("}", 4)

        size = np.prod(in_shape) if len(in_shape) > 0 else 1

        # Buffer allocation
        if len(in_shape) == 0:  # Scalar
            scalar_type = ctype_map.get(str(in_dtype), "int")
            out_str += format_str(f"{scalar_type} source_in{i};", 4)
            out_str += format_str(f"ifile{i} >> source_in{i};", 4)
        else:  # Array
            c_type = ctype_map.get(str(in_dtype), "int")
            out_str += format_str(f"vector<{c_type}> source_in{i}({size});", 4)
            out_str += format_str(f"for (int k = 0; k < {size}; k++) {{", 4)
            out_str += format_str(f"ifile{i} >> source_in{i}[k];", 8)
            out_str += format_str("}", 4)

    # Process outputs
    for i, (out_dtype, out_shape) in enumerate(outputs):
        size = np.prod(out_shape) if len(out_shape) > 0 else 1
        out_str += format_str(
            f"vector<{ctype_map.get(str(out_dtype), 'int')}> source_out{i}({size}, 0);",
            4,
        )

    out_str += "\n"

    # Call the top function
    # Note: signatures in Catapult HLS generated code generally match what we emitted.
    # Arrays are pointers or ac_channel references.
    # Scalars are values.
    # We need to construct the call arguments.

    args = []

    # Inputs
    for i, (in_dtype, in_shape) in enumerate(inputs):
        if len(in_shape) == 0:
            args.append(f"source_in{i}")
        else:
            args.append(f"source_in{i}.data()")

    # Outputs
    for i in range(len(outputs)):
        args.append(f"source_out{i}.data()")

    # Handling explicit return vs output arguments handled in `inputs` (legacy)
    # If num_output_args > 0, some inputs are actually outputs (pointers)
    # The logic in Vitis handles this.

    # Call kernel
    out_str += format_str(f"{top}({', '.join(args)});", 4)
    out_str += "\n"

    # Write outputs to files
    if len(outputs) > 0:
        for i, (_, out_shape) in enumerate(outputs):
            out_str += format_str(f'ofstream ofile{i}("output{i}.data");', 4)
            out_str += format_str(f"if (!ofile{i}) {{", 4)
            out_str += format_str(
                f'cerr << "Failed to open output file {i}!" << endl;', 8
            )
            out_str += format_str("return 1;", 8)
            out_str += format_str("}", 4)
            size = np.prod(out_shape) if len(out_shape) > 0 else 1
            out_str += format_str(f"for (int k = 0; k < {size}; k++) {{", 4)
            out_str += format_str(f"ofile{i} << source_out{i}[k] << endl;", 8)
            out_str += format_str("}", 4)
            out_str += format_str(f"ofile{i}.close();", 4)

    out_str += format_str("return 0;", 4)
    out_str += "}\n"

    return out_str



def codegen_tcl(top, configs):
    """Generate TCL script for Catapult HLS synthesis.

    Generates a hierarchical synthesis flow that preserves module boundaries
    so that per-PE and per-interconnect area/power can be extracted from reports.
    """
    frequency = configs.get("frequency", 100)
    clock_period = 1000 / frequency
    mode = configs.get("mode", "csyn")
    device = configs.get("device", "nangate-45nm_beh")
    # preserve_hier=True keeps sub-function boundaries in RTL output,
    # enabling per-module area/power breakdown in area.rpt.
    preserve_hier = configs.get("preserve_hierarchy", True)
    # sub_funcs: list of sub-function names to synthesize as separate RTL blocks.
    # Using block synthesis avoids HIER-10/HIER-47 errors (channels cross hierarchical
    # boundaries when functions are blocks, not inlined into top).
    sub_funcs = configs.get("sub_funcs", [])

    out_str = """# Project root directory
set sfd [file dir [info script]]

# Create new solution
solution new -state initial
solution options defaults
solution options set /Input/CppStandard c++11
solution options set /Input/CompilerFlags {{-D_GLIBCXX_USE_CXX11_ABI=0}}

# Add source files
solution file add "$sfd/kernel.cpp" -type C++
"""

    # Only include host.cpp for csim mode
    if mode == "csim":
        out_str += 'solution file add "$sfd/host.cpp" -type C++ -exclude true\n'

    out_str += f"""
# Set top-level design function
directive set -DESIGN_HIERARCHY {top}

# Set clock constraints
directive set -CLOCKS {{clk {{-CLOCK_PERIOD {clock_period:.1f}}}}}

# Set output language
solution options set /Output/OutputVerilog true
solution options set /Output/OutputVHDL false
"""

    # Library selection based on device
    if "45nm" in device or "nangate" in device:
        out_str += "solution library add nangate-45nm_beh\n"
    elif "sky130" in device:
        out_str += "solution library add sky130\n"
    else:
        out_str += f"solution library add {device}\n"

    out_str += """
# Flow
go analyze
"""

    # Block synthesis: keep sub-functions as separate RTL modules so channels
    # cross hierarchical boundaries (avoids HIER-10/HIER-47 errors).
    if sub_funcs:
        for fn in sub_funcs:
            out_str += f"solution design set {fn} -block\n"
        out_str += "\n"

    out_str += "go compile\n"


    if mode == "csim":
        out_str += """
solution app linkage
solution app execution
"""

    # Continue synthesis if not just csim
    if mode in {"csyn", "ppa"}:
        out_str += """
solution library add ccs_sample_mem
go assembly
"""
        out_str += "go extract\n"

    out_str += "\nexit\n"
    return out_str


def parse_catapult_report(project_path, top):
    """Parse Catapult HLS synthesis report (flat summary).

    Parameters
    ----------
    project_path : str
        Path to the project directory
    top : str
        Top-level function name

    Returns
    -------
    dict
        Parsed metrics (Area, Latency, Power).
    """
    import os
    import re

    sol_dir = os.path.join(project_path, "Catapult", f"{top}.v1")

    res = {
        "Latency (cycles)": "N/A",
        "Area": "N/A",
        "Power": "N/A",
    }

    # --- Latency from cycle.rpt ---
    cycle_rpt = os.path.join(sol_dir, "cycle.rpt")
    if not os.path.exists(cycle_rpt):
        cycle_rpt = os.path.join(project_path, f"{top}.rpt")

    if os.path.exists(cycle_rpt):
        with open(cycle_rpt, "r") as f:
            content = f.read()
        m = re.search(r"Max Latency\s*:\s*(\d+)", content)
        if m:
            res["Latency (cycles)"] = m.group(1)

    # --- Area from area.rpt ---
    area_rpt = os.path.join(sol_dir, "area.rpt")
    if os.path.exists(area_rpt):
        with open(area_rpt, "r") as f:
            area_content = f.read()
        m = re.search(r"Total Area\s*:\s*([\d\.]+)", area_content)
        if m:
            res["Area"] = m.group(1)

    # --- Power from power.rpt or summary ---
    for power_fname in ("power.rpt", "power_summary.rpt"):
        power_rpt = os.path.join(sol_dir, power_fname)
        if os.path.exists(power_rpt):
            with open(power_rpt, "r") as f:
                pwr_content = f.read()
            m = re.search(r"Total Power\s*:\s*([\d\.]+\s*\w+)", pwr_content)
            if m:
                res["Power"] = m.group(1)
            break

    return res


def parse_catapult_hierarchical_report(project_path, top):
    """Parse Catapult HLS area.rpt for per-module (hierarchical) PPA breakdown.

    Catapult writes a hierarchical area report when -PRESERVE_HIERARCHY is set.
    The report has indented module entries like:

        Module: memory_tile_2x1
          Cell Area   : 1234.56
          ...
        Module: compute_tile_2x1
          Cell Area   : 567.89

    Returns
    -------
    dict
        {
          "top": {"area": float, "cells": int},          # entire design
          "modules": {
              "<func_name>": {"area": float, "cells": int},
              ...
          },
          "summary": str,   # human-readable table
        }
    """
    import os
    import re

    sol_dir = os.path.join(project_path, "Catapult", f"{top}.v1")
    area_rpt = os.path.join(sol_dir, "area.rpt")

    result = {"top": {}, "modules": {}, "summary": "No area.rpt found."}
    if not os.path.exists(area_rpt):
        return result

    with open(area_rpt, "r") as f:
        content = f.read()

    # --- Top-level total ---
    m = re.search(r"Total Area\s*:\s*([\d\.]+)", content)
    if m:
        result["top"]["area"] = float(m.group(1))
    m = re.search(r"Total Cells\s*:\s*(\d+)", content)
    if m:
        result["top"]["cells"] = int(m.group(1))

    # --- Per-module breakdown ---
    # Catapult area.rpt format (approximate):
    #   Module: <name>
    #     Cell Area   : <value>
    #     Cell Count  : <value>
    #     Power       : <value>  (optional)
    module_blocks = re.findall(
        r"Module:\s*(\S+)(.*?)(?=Module:|\Z)", content, re.DOTALL
    )
    for mod_name, block in module_blocks:
        info = {}
        a = re.search(r"Cell Area\s*:\s*([\d\.]+)", block)
        if a:
            info["area"] = float(a.group(1))
        c = re.search(r"Cell Count\s*:\s*(\d+)", block)
        if c:
            info["cells"] = int(c.group(1))
        p = re.search(r"Power\s*:\s*([\d\.eE\+\-]+)", block)
        if p:
            info["power"] = float(p.group(1))
        if info:
            result["modules"][mod_name] = info

    # --- Human-readable summary table ---
    lines = ["Hierarchical PPA Report (Catapult HLS)", "=" * 60]
    top_area = result["top"].get("area", "N/A")
    lines.append(f"{'Module':<35} {'Area':>10} {'Cells':>8}")
    lines.append("-" * 60)
    lines.append(
        f"{'[TOP] ' + top:<35} {str(top_area):>10} "
        f"{str(result['top'].get('cells', 'N/A')):>8}"
    )
    for mod, info in result["modules"].items():
        lines.append(
            f"  {mod:<33} {str(info.get('area', 'N/A')):>10} "
            f"{str(info.get('cells', 'N/A')):>8}"
        )

    # Infer interconnect cost = top - sum(compute modules)
    module_area_sum = sum(
        v.get("area", 0) for v in result["modules"].values()
    )
    if isinstance(top_area, float) and module_area_sum > 0:
        interconnect = top_area - module_area_sum
        lines.append("-" * 60)
        lines.append(
            f"  {'[Interconnect/Overhead]':<33} {interconnect:>10.2f} {'':>8}"
        )

    result["summary"] = "\n".join(lines)
    return result
