
//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
#include <cstdint>
#include "/xls_builtin.h"
#include "xls_int.h"

template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

/// This is top function.

// ---- TestBlock with embedded function (register mode) ----
class TestBlock {
public:
  __xls_channel<int, __xls_channel_dir_In> v0_in;
  __xls_channel<int, __xls_channel_dir_In> v1_in;
  __xls_channel<int, __xls_channel_dir_Out> out;

  #pragma hls_top
  void vvadd() {
    // L2
     int v0[16];
     int v1[16];
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       v0[_idx] = v0_in.read();
     }
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       v1[_idx] = v1_in.read();
     }
     int c[16] /* int c[16] */;	// L4
     #pragma hls_unroll yes
     for (int v3 = 0; v3 < 16; v3++) {	// L5
       c[v3] = 0;	// L5
     }
     #pragma hls_pipeline_init_interval 1
     for (int i = 0; i < 16; i++) {	// L6
       int v5 = v0[i];	// L7
       int v6 = v1[i];	// L8
       ac_int<33, true> v7 = v5;	// L9
       ac_int<33, true> v8 = v6;	// L10
       ac_int<33, true> v9 = v7 + v8;	// L11
       int v10 = v9;	// L12
       c[i] = v10;	// L13
     }
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       out.write(c[_idx]);
     }

  }
};
