name: 🚀 Feature request
description: Suggest an idea for this project
title: "[Feature] "

body:
- type: textarea
  attributes:
    label: Motivation and Expected Behavior
    description: |
      Clearly and concisely describe the feature's motivation and expected behavior.
  validations:
    required: true
- type: textarea
  attributes:
    label: Related resources
    description: |
      Provide any other context about the feature request here.
  validations:
    required: false