
//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
#include <cstdint>
#include "/xls_builtin.h"
#include "xls_int.h"

template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

/// This is top function.
#pragma hls_top
int mul(
  int v0,
  int v1
) {	// L2
  long long v2 = v0;	// L3
  long long v3 = v1;	// L4
  long long v4 = v2 * v3;	// L5
  int v5 = v4;	// L6
  return v5;
}

