
// Test harness for combinational logic
#include <iostream>
#include <cstdint>

// Include the mock headers
#include "xls_builtin.h"
#include "xls_int.h"

// Wrap the ac_int alias
template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

// Generated code (remove the #include directives that reference XLS paths)

//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
#include <cstdint>

template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

/// This is top function.
#pragma hls_top
int sub(
  int v0,
  int v1
) {	// L2
  ac_int<33, true> v2 = v0;	// L3
  ac_int<33, true> v3 = v1;	// L4
  ac_int<33, true> v4 = v2 - v3;	// L5
  int v5 = v4;	// L6
  return v5;
}



int main() {

    // Test case 1
    {
        int result = sub(5, 3);
        std::cout << result << std::endl;
    }

    // Test case 2
    {
        int result = sub(3, 5);
        std::cout << result << std::endl;
    }

    // Test case 3
    {
        int result = sub(0, 0);
        std::cout << result << std::endl;
    }

    // Test case 4
    {
        int result = sub(-1, -1);
        std::cout << result << std::endl;
    }

    // Test case 5
    {
        int result = sub(100, 50);
        std::cout << result << std::endl;
    }

    return 0;
}
