# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: "Build documentation"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'docs/**'
      - 'tutorials/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'docs/**'
      - 'tutorials/**'

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    container:
      image: chhzh123/allo:llvm-19.x-py3.12

    steps:
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync
    - name: Install git
      run: |
        apt-get install -y git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    - name: Build Allo
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pip install -v -e .
    - name: Build docs
      shell: bash
      run: |
        source activate allo
        export PATH=/root/llvm-project/build/bin:${PATH}
        cd docs
        python3 -m pip install -r requirements.txt
        make html
    - run: touch docs/build/html/.nojekyll
    # Create an artifact of the html output using Github action: https://github.com/actions/upload-artifact
    - uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/build/html/
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.event_name == 'push'
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html/
