
// Test harness for sequential logic with channels
#include <iostream>
#include <cstdint>

// Include the mock headers
#include "xls_builtin.h"
#include "xls_int.h"

// Wrap the ac_int alias
template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

// Generated code (remove the #include directives that reference XLS paths)

//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
#include <cstdint>

template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

/// This is top function.

// ---- TestBlock with embedded function (register mode) ----
class TestBlock {
public:
  __xls_channel<int, __xls_channel_dir_In> v0_in;
  __xls_channel<int, __xls_channel_dir_In> v1_in;
  __xls_channel<int, __xls_channel_dir_Out> out;

  #pragma hls_top
  void mv() {
    // L2
     int v0[4][4];
     int v1[4];
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 16; ++_idx) {
       v0[_idx / 4][_idx % 4] = v0_in.read();
     }
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 4; ++_idx) {
       v1[_idx] = v1_in.read();
     }
     int y[4] /* int y[4] */;	// L4
     #pragma hls_unroll yes
     for (int v3 = 0; v3 < 4; v3++) {	// L5
       y[v3] = 0;	// L5
     }
     #pragma hls_pipeline_init_interval 1
     for (int i = 0; i < 4; i++) {	// L6
       y[i] = 0;	// L7
       #pragma hls_unroll yes
       for (int j = 0; j < 4; j++) {	// L8
         int v6 = v0[i][j];	// L9
         int v7 = v1[j];	// L10
         long long v8 = v6;	// L11
         long long v9 = v7;	// L12
         long long v10 = v8 * v9;	// L13
         int v11 = y[i];	// L14
         int v12 = v10;	// L15
         int v13 = v11 + v12;	// L16
         y[i] = v13;	// L17
       }
     }
     #pragma hls_pipeline_init_interval 1
     for (int _idx = 0; _idx < 4; ++_idx) {
       out.write(y[_idx]);
     }

  }
};


int main() {
    TestBlock block;
    
    block.v0_in.push_input(1);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(2);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(3);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(0);
    block.v0_in.push_input(4);
    block.v1_in.push_input(1);
    block.v1_in.push_input(2);
    block.v1_in.push_input(3);
    block.v1_in.push_input(4);

    // Run the function multiple times to process all data
    for (int i = 0; i < 124; i++) {
        try {
            block.mv();
        } catch (...) {
            // Input channels may be empty
        }
    }
    
    // Read output data
    for (int i = 0; i < 4; i++) {
        try {
            int val = block.out.pop_output();
            std::cout << val << " ";
        } catch (...) {
            std::cout << "ERR ";
        }
    }
    std::cout << std::endl;
    
    return 0;
}
